conversation_list_db = {
    'random': [
        'What was the last funny video you saw?',
        'What do you do to get rid of stress?',
        'What is something you are obsessed with?',
        'What three words best describe you?',
        'What would be your perfect weekend?',
        'What do you think of tattoos? Do you have any?',
        'What’s your favorite number? Why?',
        'What’s the most useful thing you own? ',
        'What’s your favorite way to waste time?',
        'Do you have any pets? What are their names?',
        'Where did you go last weekend? / What did you do last weekend?',
        'What are you going to do this weekend?',
        'What is something popular now that annoys you?',
        'What did you do on your last vacation?',
        'When was the last time you worked incredibly hard?',
        'Are you very active, or do you prefer to just relax in your free '
        'time?',
        'What do you do when you hang out with your friends?',
        'Who is your oldest friend? Where did you meet them?',
        'What’s the best / worst thing about your work/school?',
        'If you had intro music, what song would it be? Why?',
        'What were you really into when you were a kid?',
        'If you could have any animal as a pet, what animal would you choose?',
        'Have you ever saved an animal’s life? How about a person’s life?',
        'If you opened a business, what kind of business would it be?',
        'Who is your favorite entertainer (comedian, musician, actor, etc.)?',
        'Are you a very organized person?',
        'Have you ever given a presentation in front of a large group of '
        'people? How did it go?',
        'What is the strangest dream you have ever had?',
        'What is a controversial opinion you have?',
        'Who in your life brings you the most joy?',
        'Who had the biggest impact on the person you have become?',
        'What is the most annoying habit someone can have?',
        'Where is the most beautiful place you have been?',
        'Where do you spend most of your free time/day?',
        'Who was your best friend in elementary school?',
        'How often do you stay up past a.m.?',
        'What’s your favorite season? Why?',
        'Which is more important, having a great car or a great house? Why?',
        'What animal or insect do you wish humans could eradicate?',
        'Where is the most beautiful place near where you live?',
        'What do you bring with you everywhere you go?',
        'How much time do you spend on the internet? What do you usually do?',
        'What is the most disgusting habit some people have?',
        'Where and when was the most amazing sunset you have ever seen?',
        'Which ',
        'Where is the worst place you have been stuck for a long time?',
        'If you had to change your name, what would your new name be?',
        'What is something that really annoys you but doesn’t bother most '
        'people?',
        'What word or saying from the past do you think should come back?',
        'How should success be measured? And by that measurement, who is the '
        'most successful person you know?',
        'What is your guilty pleasure?',
        'Was there ever an event in your life that defied explanation?',
        'If you could learn the answer to one question about your future, what '
        'would the question be?',
        'Has anyone ever saved your life?',
        'What benefit do you bring to the group when you hang out with '
        'friends?',
        'How often do you curse? And what’s your go-to string of curse words?',
        'What trends did you follow when you were younger?',
        'What do you fear is hiding in the dark?',
        'What was the best period of your life so far? What do you think will '
        'be the best period of your entire life?',
        'What do you do to improve your mood when you are in a bad mood?',
        'What is the silliest fear you have?',
        'What are some things you want to accomplish before you die?',
        'What is the best room in your house? Why?',
        'Who is someone popular now that you really like? Why do you like them '
        'so much?',
        'Where is the best place to take a date?',
        'What smell brings back great memories?',
        'What’s the best pet name you can come up with for a specific type of '
        'pet? (Like these ',
        'How often do you help others? Who do you help? How do you help?',
        'What are you best at?',
        'What makes you nervous?',
        'Who is the funniest person you’ve met?',
        'What weird or useless talent do you have?',
        'What are some strange beliefs that some people have?',
        'Who would be the worst person to be stuck in an elevator with? How '
        'about the best person to be stuck in an elevator with?',
        'What was the best birthday wish or gift you’ve ever received?'
        'Who was your best teacher?',
        'What charity or social issue is most important to you and why?',
        'Is there something you’ve dreamed of doing for a long time? What’s kept you from it?',
        'What’s something you wish you were really good at?',
        'What did you want to be when you grew up?',
        'What’s something you love about your hometown?'
    ],
    'tv': ['What’s the funniest TV series you have seen?',
           'Which TV show do you want your life to be like?',
           'If you could bring back one TV show that was canceled, which one '
           'would you bring back?',
           'How have TV shows changed over the years?',
           'What’s the best sitcom past or present?',
           'What’s the best show currently on TV?',
           'What do you think about game shows? Do you have a favorite one?',
           'What’s the most underrated or overrated TV show?',
           'What do you think about reality TV? Why do you think it’s so popular?',
           'Do you like reality TV shows? Why or why not? If so, which ones?',
           'What will be the future of TV shows?',
           'How often do you binge watch shows?',
           'What cartoons did you watch as a child?'],
    'apps': ['What are the three best apps on your phone?',
             'What is the most useful app on your phone?',
             'What’re the best and worst things about the marketplace where you '
             'get your apps?',
             'What do app makers do that really annoys you?',
             'How many apps do you have on your phone?',
             'What’s the most frustrating app you have tried?',
             'What’s the most addictive mobile game you have played?',
             'Which app seemed like magic the first time you used it?',
             'What is the strangest app you have heard of or tried?',
             'Which app has helped society the most? Which one has hurt society '
             'the most?',
             'An app mysteriously appears on your phone that does something '
             'amazing. What does it do?'],
    'books': ['What was the last book you read?',
              'What was your favorite book as a child?',
              'Do you prefer physical books or ebooks?',
              'What is the longest book you’ve read?',
              'What book genres do you like to read?',
              'Do you prefer fiction or nonfiction books?',
              'What book has influenced you the most?',
              'How fast do you read?',
              'How often do you go to the library?',
              'What book has changed one of your long-held opinions?',
              'What book has had the biggest effect on the modern world?',
              'What was the worst book you had to read for school? How about the '
              'best book you had to read for school?',
              'Do you think people read more or fewer books now than years ago?',
              'Now that indie publishing has become easier, have books gotten '
              'better or worse?'],
    'clothes': ['What is your favorite shirt?',
                'Does fashion help society in any way?',
                'What old trend is coming back these days?',
                'What is a fashion trend you are really glad went away?',
                'What is the most comfortable piece of clothing you own?',
                'What is the most embarrassing piece of clothing you own?',
                'How do clothes change how the opposite sex views a person?',
                'Do you care about fashion? What style of clothes do you usually '
                'wear?',
                'If you didn’t care at all what people thought of you, what '
                'clothes would you wear?',
                'What is the best pair of shoes you have ever owned? Why were '
                'they so good?',
                'Who do you think has the biggest impact on fashion trends: '
                'actors and actresses, musicians, fashion designers, or '
                'consumers?'],
    'education': ['What do you think of online education?',
                  'How can governments make education more efficient?',
                  'What do you think of standardized tests?',
                  'Are bigger or smaller schools better?',
                  'Is teaching a skill that can be taught?',
                  'What will the future of education be?',
                  'What do you think of homeschooling?',
                  'How has the education you received changed your life?',
                  'How can technology improve education? Can it hurt education?',
                  'What or who has taught you most of the information you use '
                  'regularly?',
                  'What are some good and bad things about the education system '
                  'in your country?'],
    'deep': [
        'What was one of the best gifts you received as a child?',
        'Do you have any goals you\'d like to accomplish this year?',
        'What is the most thrilling thing you\'ve ever done?',
        'What do you like to do when you have alone time?',
        'What\'s your worst habit?',
        'What calms you down when you\'re stressed or upset?',
        'Is there anyone you look up to?',
        'What can a person do to make you unattracted to them, no matter how attractive they are?',
        'Is there a friend you wish you were closer to?',
        'What\'s something you look forward to every day?',
        'Describe your ideal morning routine.',
        'Describe yourself in only three words.',
        'Share a happy memory.',
        'Is there something for which you\'ve been mocked, that later became a strength?',
        'What were you like as a student?',
        'Did you have a mentor growing up? How did they influence you?',
        'What has been the best part of your day so far?',
        'What\'s the most embarrassing thing that has happened to you?',
        'How have you changed in the past five years?',
        'How do you define success?',
        'Are you more like one of your parents? Which one?',
        'Do you have any habits you want to change?',
        'What\'s been the best thing to happen in your life so far?',
    ],
    'food': ['What is your favorite cuisine or type of food?',
             'What foods do you absolutely hate?',
             'What do you think of buffets?',
             'When was the last time you had a food fight?',
             'What food looks disgusting but tastes delicious?',
             'What do you get every time you go grocery shopping?',
             'If your life was a meal, what would kind of meal would it be?',
             'What would you want your last meal to be if you were on ',
             'What food do you know you shouldn’t eat but can’t stop yourself?',
             'Do you like spicy food? Why or why not? What is the spiciest thing '
             'you have ever eaten?',
             'Does the government have a place in regulating food? To what extent '
             'should government regulate food? ',
             'When people make mistakes about food (especially foreign food), do '
             'you feel the need to correct them? (i.e. '],
    'funny': [
        'Are you superstitious? About what?',
        'What is your favorite fast food restaurant?',
        'If your pet could answer one question, what would you ask them?',
        'Is a hotdog a sandwich? Is cereal a soup?',
        'Which real animal would you ride, given the chance?',
        'What\'s something everyone likes that you don\'t?',
        'What\'s your favorite swear word?',
        'What was your favorite cartoon as a kid?',
        'Do you have a hidden talent? What is it?',
        'If you could have any magical power, what would it be?',
        'What three items could you purchase that would make a cashier the most uncomfortable?',
        'What is the dumbest way you\'ve ever injured yourself?',
        'What\'s your favorite board game?',
        'Would you ever ride in a hot air balloon?',
        'What song instantly gets you hyped up?',
        'Describe your ideal party.',
        'Do you collect anything? What is it?',
    ],
    'goals': ['What personal goals do you have?',
              'What are your goals for the next two years?',
              'How have your goals changed over your life?',
              'How much do you plan for the future?',
              'How do you plan to make the world a better place?',
              'What are some goals you have already achieved?',
              'What do you hope to achieve in your professional life?',
              'Have your parents influenced what goals you have?',
              'Do you usually achieve the goals you set? Why or why not?',
              'What is the best way to stay motivated and complete goals?',
              'What are some goals you have failed to accomplish?',
              'What is the craziest, most outrageous thing you want to achieve?',
              'When do you want to retire? What do you want to do when you '
              'retire?'],
    'holidays': ['What is the biggest holiday for your family?',
                 'What is your favorite holiday?',
                 'What holidays have been over-commercialized?',
                 'Do you wish there were more or fewer holidays? Why?',
                 'What do you know about the history of some holidays?',
                 'What kinds of food do you usually eat on your favorite holiday?',
                 'If you had to get rid of a holiday, which would you get rid of? '
                 'Why?',
                 'Does having a day off for a holiday increase or decrease '
                 'productivity at work?',
                 'If some of the lesser-known holidays were commercialized, what '
                 'would the commercialization look like?',
                 'If you could make a holiday, what would it be like? What '
                 'traditions would it have? What would people eat on your '
                 'holiday?'],
    'light': [
        'What\'s your favorite karaoke song?',
        'If you were to visit another country for a month, where would you go and why?',
        'What was your first cell phone?',
        'Who is the most famous person you\'ve ever met?',
        'What is the last book you read? Would you recommend it?',
        'What was the first CD you owned?',
        'Do you have a favorite scent?',
        'What was your first job?',
        'What was your best job ever? Your worst?',
        'What animal would you love to have as a pet?',
        'What\'s something that makes you feel fancy?',
        'Which movie can you recite by heart?',
        'Is there a project you\'ve started, but haven\'t finished?',
        'What would you do with an extra $500 that you could only spend on yourself?',
        'Would you change your first name? What would you change it to?',
        'What reality TV show would you want to go on?',
        'What food do you hate the most? Why?',
        'What was the last thing you made?',
        'What\'s the saddest movie you\'ve ever seen?',
        'Where is the most beautiful place you\'ve ever been?',
        'Where\'s somewhere you visited that was better that you expected?',
        'What was your most memorable vacation?',
        'If you could have dinner with anyone famous, who would it be?',
        'What was the last show you binge watched?',
        'What was the last concert you went to?',
        'What\'s the most spontaneous thing you\'ve ever done?',
        'What\'s your favorite sport to play? To watch?',
        'What dish do you love to cook or bake?',
        'What\'s your favorite outdoor activity?',
        'What\'s a food that you\'d really like to try?',
        'Have you ever won anything in a contest? What was it?'
        'What\'s a podcast that you\'d recommend?',
    ],
    'movies': ['What is the most overrated movie?',
               'What’s your favorite genre of movie?',
               'Which do you prefer? Books or movies?',
               'What movie scene choked you up the most?',
               'Do you like documentaries? Why / why not?',
               'What’s the worst movie you have seen recently?',
               'What’s the strangest movie you have ever seen?',
               'Do you like horror movies? Why or why not?',
               'When was the last time you went to a movie theater?',
               'What was the last movie you watched? How was it?',
               'Do movies have the same power as books to change the world?',
               'Do you prefer to watch movies in the theater or in the comfort of '
               'your own home?'],
    'music': ['What song always puts you in a good mood?',
              'What’s the best way to discover new music?',
              'What was the last song you listened to?',
              'What is your favorite movie soundtrack?',
              'Do you like classical music?',
              'How has technology changed the music industry?',
              'Are there any songs that always bring a tear to your eye?',
              'What bands or types of music do you listen to when you exercise?',
              'Which do you prefer, popular music or relatively unknown music?',
              'Do you like going to concerts? Why or why not? What was the last '
              'concert you went to?',
              'Who was the first band or musician you were really into? Do you '
              'still like them?',
              'Records, tapes, CDs, MP, streaming. Which did you grow up with? '
              'What is good and bad about each?'],
    'phones': ['How often do you check your phone?',
               'Do you always have to have the latest phone?',
               'Do you text more or call more? Why?',
               'What will phones be like in years?',
               'What is the most annoying thing about your phone?',
               'How do you feel if you accidentally leave your phone at home?',
               'What do you wish your phone could do?',
               'What kind of case do you have for your phone? Why did you choose '
               'it?',
               'What was your first smartphone? How did you feel when you got it?',
               'Do you experience phantom vibration? (Feeling your phone vibrate '
               'even though it didn’t.)'],
    'restaurants': ['What restaurant do you eat at most?',
                    'What’s the worst fast food restaurant?',
                    'What is the best restaurant in your area?',
                    'What is the fanciest restaurant you have eaten at?',
                    'What kind of interior do you like a restaurant to have?',
                    'What is the worst restaurant you have ever eaten at?',
                    'If you opened a restaurant, what kind of food would you '
                    'serve?',
                    'What is the strangest themed restaurant you have heard of?',
                    'Would you eat at a restaurant that was really dirty if the '
                    'food was amazing?',
                    'What is the most disgusting thing you have heard happened at '
                    'a restaurant?',
                    'What was your favorite restaurant when you were a child?'],
    'romantic': [
        'When was a time I impressed you?',
        'What adventure would you like to take together?',
        'What\'s your favorite outfit or garment I wear?',
        'Where is your favorite place to visit together?',
        'Describe a funny moment we\'ve shared.',
        'Describe why you\'re thankful for the person you\'re answering these questions with.',
        'What\'s something I introduced you to that you now like?',
        'What\'s your favorite activity to do together?',
        'What\'s the best gift I\'ve given you?',
        'What do you admire most about me?',
        'What\'s something you wish I would do more of?',
        'What was your first kiss like?',
        'What\'s the worst date you\'ve ever been on?',
        'What\'s your Love Language?',
        'What was your first impression of me when we met?',
        'What song always reminds you of me?',
        'What\'s something I do that makes you feel loved?',
    ],
    'seasons': ['Do you prefer summer or winter activities?',
                'What do you like to do in the spring?',
                'Did your family take seasonal vacations?',
                'Which do you prefer, fall or spring?',
                'Which season are you most active in?',
                'What’s the most refreshing thing on a hot summer day?',
                'What’s the best thing to do on a cold winter day?',
                'Where is the nicest place you have been to in fall?',
                'What is your favorite thing to eat or drink in winter?',
                'Is it better to live where there are four seasons or where one '
                'season takes up most of the year?'],
    'sports': ['What sports do you like to watch?',
               'Who are some of your favorite athletes?',
               'Which sports do you like to play',
               'What is the hardest sport to excel at?',
               'Who are the greatest athletes of all time?',
               'Do you play in any fantasy sports leagues? If so, how into '
               'fantasy sports are you?',
               'How much time do you spend watching sports in a week?',
               'Do athletes deserve the high salaries they receive? Why or why '
               'not?',
               'What defines a sport? Is fishing a sport? How about video game '
               'tournaments?',
               'Why do you think sports are common across almost all cultures '
               'present and past?',
               'Do you play sports video games? Which ones? Is playing the video '
               'game or playing the sport more fun? Why?',
               'Which sport is the most exciting to watch? Which is the most '
               'boring to watch?'],
    'technology': ['What is your favorite piece of technology that you own?',
                   'What piece of technology is really frustrating to use?',
                   'What was the best invention of the last years?',
                   'Does technology simplify life or make it more complicated?',
                   'Will technology save the human race or destroy it?',
                   'Which emerging technology are you most excited about?',
                   'What sci-fi movie or book would you like the future to be '
                   'like?',
                   'What do you think the next big technological advance will be?',
                   'What technology from a science fiction movie would you most '
                   'like to have?',
                   'What problems will technology solve in the next years? What '
                   'problems will it create?',
                   'What piece of technology would look like magic or a miracle '
                   'to people in medieval Europe?',
                   'Can you think of any technology that has only made the world '
                   'worse? How about a piece of technology that has only made the '
                   'world better?'],
    'travel': ['Where would you like to travel next?',
               'What is the longest plane trip you have taken?',
               'What’s the best way to travel? (Plane, car, train, etc.)',
               'Where is the most relaxing place you have been?',
               'Do you prefer traveling alone or with a group?',
               'What do you think of tour group packages?',
               'Do you prefer to go off the beaten path when you travel?',
               'What was the most overhyped place you’ve traveled to?',
               'Have you traveled to any different countries? Which ones?',
               'Where is the most awe-inspiring place you have been?',
               'What’s the best thing about traveling? How about the worst thing?',
               'What is the worst hotel you have stayed at? How about the best '
               'hotel?',
               'How do you think traveling to a lot of different countries '
               'changes a person?',
               'Talk about some of the interesting people you have met while '
               'traveling.',
               'What do you think of staycations? (Vacationing and seeing tourist '
               'attractions where you live.)',
               'Where do you get your recommendations for what to do and where to '
               'stay when you travel?'],
    'weird': ['If your mind were an island, what would it look like?',
              'What flavor of ice cream do you wish existed?',
              'If you had a personal mascot, what would your mascot be?',
              'If you were a king/queen, what would your throne look like?',
              'Time freezes for everyone but you for one day. What do you do?',
              'You have to relive one day of your life forever. Which day do you '
              'choose?',
              'What does your own personal hell look like? How about your own '
              'personal heaven?',
              'You find a remote that can rewind, fast forward, stop, and start '
              'time. What do you do with it?',
              'If you could call up anyone in the world and have a one-hour '
              'conversation, who would you call?',
              'The world has become infested with rabid dogs with the '
              'intelligence of a year-old, where do you hole up to survive the '
              '“a-pup-calypse”?',
              'A portal to another world opens in front of you. You don’t know '
              'how long it will stay open or if you’ll be able to get back after '
              'you go through. What do you do?']
}
