from enum import Enum


class Topic(str, Enum):
    random = 'random'
    tv = 'tv'
    apps = 'apps'
    books = 'books'
    clothes = 'clothes'
    education = 'education'
    deep = 'deep'
    food = 'food'
    funny = 'funny'
    goals = 'goals'
    holidays = 'holidays'
    light = 'light'
    movies = 'movies'
    music = 'music'
    phones = 'phones'
    restaurants = 'restaurants'
    romantic = 'romantic'
    seasons = 'seasons'
    sports = 'sports'
    technology = 'technology'
    travel = 'travel'
    weird = 'weird'
